### ISSUE TITLE
Add translation to the Info Dialog

### ISSUE THREAD

**Issue by tochman** [AgileVentures/senf_client#103]

**Comment by tochman** [comment]
```
As a user
In order to be able to fully understand the content of the application
I would like the UI to present English content if my default browser language is NOT german
```

The `navigator` object can reveal what language setting our visitors has. Based on that, we can make a decision on the UI language.

**Comment by tassilomorino** [comment]
maybe like this:

https://images.zenhubusercontent.com/60f47913ad515f9e4c4346e5/5b7175ea-984f-42ab-a76d-4af838a0b449

**Comment by tassilomorino** [comment]
for transslation we could use: https://www.deepl.com/

**Comment by tassilomorino** [comment]
should we use i18next? https://react.i18next.com/getting-started
