### ISSUE TITLE
Better Select Form

### ISSUE THREAD

**Issue by tassilomorino** [AgileVentures/senf_client#104]
As a user,
in order to have a great user experience using the select forms within the application,
I would like to see a responsive select form that adjusts in size to it's content, has a custom icon on the right side and opens a beautiful select modal.

at the moment it might be looking like this:
https://images.zenhubusercontent.com/60f47913ad515f9e4c4346e5/07a71f6b-433b-4449-ac38-3a410c9d2587

**Comment by tassilomorino** [comment]
This is a great example of how it should look like! ![image](https://images.zenhubusercontent.com/60f47913ad515f9e4c4346e5/b515b4a6-babc-4b8e-bf79-450262b7b53f)

**Comment by wordhouse66** [comment]
ok.
