### ISSUE TITLE
Signupform Validators

### ISSUE THREAD

**Issue by tassilomorino** [AgileVentures/senf_client#200]
Path:
/components/atoms/Auth/RegistrationAndLogin.jsx

from line 261 function handleSubmitRegister

As a systemowner,
in order to ensure a correct signup process,
I want to be able to present users errors and error-messages, when they didn't fill up the signup correctly.

– Formfields shall light up with an error if not filled, and an. error-message shall show under the forms-section

– Email shall be in an email format
– Password shall have at least 8 Characters (and shouldnt be without big letter, number)
– Confirmpassword shall match password, (maybe that could also light up)
– Username should be only characters and numbers (no spaces, no other symbols)
– Birthyear and gender is optional

**Comment by Digital-Coder** [comment]
has been implemented, thanks for a suggestion :D
