### ISSUE TITLE
Bug: When searching ideas, within the ideaCard, the projectroombar disappears.

### ISSUE THREAD

**Issue by tassilomorino** [AgileVentures/senf_client#314]

**Comment by Digital-Coder** [comment]
![Bild von iOS (1)](https://user-images.githubusercontent.com/31192965/155143236-d5f7481d-4aa0-4aa5-9c5d-1bcd76e8fe18.png)
![Bild von iOS](https://user-images.githubusercontent.com/31192965/155143279-b6356b68-c2e3-4e0d-b011-84e3cb6e7dd7.png)
